### ISSUE TITLE
change peerflix path

### ISSUE THREAD

**Issue by kalimeroo** [JimmyLaurent/snatchflix#1]
Hi,

Thank you for this program. Is it possible to change the path where the files are saved by peerflix (defaults to tmp directory) ?

Thanks

**Comment by FonkyCorp** [comment]
Hi, sorry I don't plan improvements for this program but you can take a look at "wget-torrent" also available on npm registry.
I's a kind of snatchflix V2 with new features.
There is an option to specify a path like you want.

It's still a work in progress but it's functional.

**Comment by kalimeroo** [comment]
Hi, thanks for the reply. I'll have a look at wget-torrent.

**Comment by JimmyLaurent** [comment]
I thought about it again and there is a way of doing it, you can specify a path via the configuration file.

Open the conf file: snatchflix --config=your_editor
And replace this line : "peerflixCommand": "peerflix"
Whith this: "peerflixCommand": "peerflix --path=D:\\Your\\Path\\Here"

**Comment by kalimeroo** [comment]
Hi,

Thanks for the hint. Adding "peerflixCommand": "peerflix --path=/videos/" leads to an error. However adding "peerflixPath": "/videos/" does exactly what I want.
Thanks for pointing me towards the solution
